### ISSUE TITLE
При добавлении отрицательного значения в метод play класса Player не выдаётся ошибка

### ISSUE THREAD

**Issue by GeneralovDV** [bloody-slipper/team-project#6]
# Описание 

При добавлении отрицательного значения в метод play не выдаётся ошибка Exception

# Локализация дефекта

https://github.com/bloody-slipper/team-project/blob/0afecfe34fb32f8acd5457304a8b5326fda01854/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/bloody-slipper/team-project/blob/0afecfe34fb32f8acd5457304a8b5326fda01854/src/main/java/ru/netology/Player.java) в IDEA
2. Запустить тест addPlayGameNegativeValue
3. Посмотреть на вывод в консоли

* Ожидаемый результат: выводится ошибка 
* Фактический результат: не выводится ошибка

# Скриншот

![2022-08-30_12-53-19](https://user-images.githubusercontent.com/105727613/187407621-0a8c6020-30b7-4f6d-846c-cccfb7f56c91.png)

# Окружение

* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA Community Edition2022.1.2
* **Java:** OpenJDK 11

**Comment by bloody-slipper** [comment]
Нет ошибки, при установке игры присваивается значение 0, далее только суммируется. Отрицательные значения не добавляются
